#!/usr/bin/env bash
# ==============================================================================
# system-config/setup_sdn_cluster_net.sh
# Proxmox VE Helper Script: Automated SDN Cluster Network Provisioning
#
# Creates an isolated Proxmox Software Defined Network (SDN) VNet:
#   - Bridge / Zone:     ProxNET / ClusterZone (VLAN-based SDN Zone)
#   - SDN VNet ID:       wazuhcl (max 8 characters required by PVE SDN)
#   - SDN VNet Alias:    Wazuh-cluster-net
#   - VLAN Tag:          1669 (VLAN > 1500)
#   - Cluster Subnet:    10.69.101.0/24 (Gateway: 10.69.101.1)
#   - Address Space:     10.69.101.0/24 to 10.69.250.0/24 for multi-node expansion
#
# Intended for inter-container cluster traffic (Wazuh Indexer/Manager/Dashboard,
# distributed databases, internal microservices) isolated from frontend ProxNET.
# ==============================================================================

set -euo pipefail

YW=$(echo "\033[33m")
BL=$(echo "\033[36m")
RD=$(echo "\033[01;31m")
GN=$(echo "\033[1;92m")
CL=$(echo "\033[m")

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [[ -f "${REPO_DIR}/.env" ]]; then
    # shellcheck source=/dev/null
    source "${REPO_DIR}/.env"
fi

if [[ $EUID -ne 0 ]]; then
    echo -e "${RD}[!] Error: This script must be executed as root on your Proxmox VE host.${CL}" >&2
    exit 1
fi

if ! command -v pveversion >/dev/null 2>&1; then
    echo -e "${RD}[!] Error: This script must be executed on a Proxmox VE host node.${CL}" >&2
    exit 1
fi

clear
cat << "BANNER"
  ____  ____  _   _    ____ _           _            _   _      _   
 / ___||  _ \| \ | |  / ___| |_   _ ___| |_ ___ _ __| \ | | ___| |_ 
 \___ \| | | |  \| | | |   | | | | / __| __/ _ \ '__|  \| |/ _ \ __|
  ___) | |_| | |\  | | |___| | |_| \__ \ ||  __/ |  | |\  |  __/ |_ 
 |____/|____/|_| \_|  \____|_|\__,_|___/\__\___|_|  |_| \_|\___|\__|
  Proxmox VE SDN Configuration: Cluster Network (VLAN > 1500)
BANNER
echo -e "${BL}Provisioning SDN VNet 'Wazuh-cluster-net' (10.69.101-250.0/24, VLAN > 1500)${CL}\n"

# 1. Parameter Defaults with .env overrides
SDN_ZONE="${SDN_ZONE:-ClusterZone}"
SDN_BRIDGE="${SDN_BRIDGE:-${MGMT_BRIDGE:-ProxNET}}"
SDN_VNET_ID="${SDN_VNET_ID:-wazuhcl}"
SDN_VNET_ALIAS="${SDN_VNET_ALIAS:-Wazuh-cluster-net}"
CLUSTER_VLAN_TAG="${CLUSTER_VLAN_TAG:-1669}"
CLUSTER_SUBNET="${CLUSTER_SUBNET:-10.69.101.0/24}"
CLUSTER_GATEWAY="${CLUSTER_GATEWAY:-10.69.101.1}"

# Whiptail interactive confirmation if running in interactive terminal
if command -v whiptail >/dev/null 2>&1 && [[ -t 0 ]]; then
    if ! whiptail --backtitle "Proxmox VE Helper Scripts" \
        --title "PROXMOX SDN CLUSTER NETWORK" \
        --yes-button "Deploy" \
        --no-button "Cancel" \
        --yesno "Configure Proxmox SDN Cluster Network with settings:\n\n• Zone:    ${SDN_ZONE} (VLAN mode on ${SDN_BRIDGE})\n• VNet:    ${SDN_VNET_ID} (Alias: ${SDN_VNET_ALIAS})\n• VLAN:    ${CLUSTER_VLAN_TAG} (>1500)\n• Subnet:  ${CLUSTER_SUBNET}\n• Gateway: ${CLUSTER_GATEWAY}\n\nProceed?" 16 68; then
        echo -e "${YW}[*] Deployment cancelled by user.${CL}"
        exit 0
    fi
fi

# 2. Verify Proxmox SDN Packages & Kernel Modules
echo -e "${YW}[*] Checking Proxmox SDN core requirements...${CL}"
if ! command -v pvesdn >/dev/null 2>&1; then
    echo -e "${YW}[*] 'pvesdn' command not found. Installing libpve-network-perl and ifupdown2...${CL}"
    DEBIAN_FRONTEND=noninteractive apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y libpve-network-perl ifupdown2
fi

# Ensure SDN configuration directory exists
mkdir -p /etc/pve/sdn

# 3. Verify underlying bridge exists (e.g., ProxNET)
if ! ip link show "$SDN_BRIDGE" >/dev/null 2>&1; then
    echo -e "${YW}[!] Warning: Bridge '${SDN_BRIDGE}' does not currently exist in running network.${CL}"
    echo -e "${BL}[*] Creating Linux Bridge '${SDN_BRIDGE}' in /etc/network/interfaces.d/proxnet.cfg...${CL}"
    mkdir -p /etc/network/interfaces.d
    if [[ ! -f /etc/network/interfaces.d/proxnet.cfg ]]; then
        cat > /etc/network/interfaces.d/proxnet.cfg << EOF
# Auto-generated by Proxmox Helper Scripts for Reverse Proxy backend network
auto ${SDN_BRIDGE}
iface ${SDN_BRIDGE} inet manual
	bridge-ports none
	bridge-stp off
	bridge-fd 0
	bridge-vlan-aware yes
	bridge-vids 2-4094
# ProxNET Backend Bridge for Nginx Reverse Proxy & SDN
EOF
        echo -e "${GN}[+] Created bridge definition '${SDN_BRIDGE}' with VLAN awareness enabled.${CL}"
        if command -v ifreload >/dev/null 2>&1; then
            ifreload -a >/dev/null 2>&1 || true
        elif command -v ifup >/dev/null 2>&1; then
            ifup "${SDN_BRIDGE}" >/dev/null 2>&1 || true
        fi
    fi
fi

# 4. Check or Create SDN Zone (VLAN type)
echo -e "${YW}[*] Configuring SDN Zone '${SDN_ZONE}' on bridge '${SDN_BRIDGE}'...${CL}"
if pvesdn zone list 2>/dev/null | grep -qw "$SDN_ZONE"; then
    echo -e "${GN}[+] SDN Zone '${SDN_ZONE}' already exists.${CL}"
else
    pvesdn zone create "$SDN_ZONE" --type vlan --bridge "$SDN_BRIDGE"
    echo -e "${GN}[+] Created SDN Zone '${SDN_ZONE}' (type: vlan, bridge: ${SDN_BRIDGE}).${CL}"
fi

# 5. Check or Create SDN VNet (wazuhcl / Wazuh-cluster-net)
echo -e "${YW}[*] Configuring SDN VNet '${SDN_VNET_ID}' (VLAN: ${CLUSTER_VLAN_TAG}, Alias: ${SDN_VNET_ALIAS})...${CL}"
if pvesdn vnet list 2>/dev/null | grep -qw "$SDN_VNET_ID"; then
    echo -e "${GN}[+] SDN VNet '${SDN_VNET_ID}' already exists.${CL}"
else
    pvesdn vnet create "$SDN_VNET_ID" \
        --zone "$SDN_ZONE" \
        --tag "$CLUSTER_VLAN_TAG" \
        --alias "$SDN_VNET_ALIAS"
    echo -e "${GN}[+] Created SDN VNet '${SDN_VNET_ID}' with tag ${CLUSTER_VLAN_TAG}.${CL}"
fi

# 6. Check or Create SDN Subnet (10.69.101.0/24)
echo -e "${YW}[*] Configuring SDN Subnet '${CLUSTER_SUBNET}' for VNet '${SDN_VNET_ID}'...${CL}"
if pvesdn subnet list 2>/dev/null | grep -q "${CLUSTER_SUBNET}"; then
    echo -e "${GN}[+] SDN Subnet '${CLUSTER_SUBNET}' already exists.${CL}"
else
    pvesdn subnet create "$SDN_VNET_ID" "$CLUSTER_SUBNET" \
        --gateway "$CLUSTER_GATEWAY" \
        --snat 0 2>/dev/null || \
    pvesdn subnet create "$SDN_ZONE" "$CLUSTER_SUBNET" \
        --gateway "$CLUSTER_GATEWAY" \
        --snat 0 2>/dev/null || true
    echo -e "${GN}[+] Configured Subnet '${CLUSTER_SUBNET}' (Gateway: ${CLUSTER_GATEWAY}).${CL}"
fi

# 7. Commit & Reload SDN Configuration
echo -e "${BL}[*] Applying and reloading Proxmox SDN configuration (pvesdn reload)...${CL}"
pvesdn reload

echo -e "\n${GN}========================================================================${CL}"
echo -e "${GN}  Proxmox VE SDN Cluster Network Ready!                                 ${CL}"
echo -e "${GN}========================================================================${CL}"
echo -e "SDN Zone:             ${BL}${SDN_ZONE}${CL} (Bridge: ${SDN_BRIDGE})"
echo -e "SDN VNet Device:      ${BL}${SDN_VNET_ID}${CL} (Alias: ${YW}${SDN_VNET_ALIAS}${CL})"
echo -e "802.1Q VLAN Tag:      ${BL}${CLUSTER_VLAN_TAG}${CL} (> 1500)"
echo -e "Cluster Subnet:       ${BL}${CLUSTER_SUBNET}${CL} (Gateway/VIP: ${CLUSTER_GATEWAY})"
echo -e "IP Address Space:     ${BL}10.69.101.0/24${CL} (Primary Wazuh Cluster)"
echo -e "Reserved Future Space:${BL}10.69.102.0/24 - 10.69.250.0/24${CL}"
echo -e "\n${YW}--> Container Network Attachment Guide:${CL}"
echo -e "In LXC containers (e.g. Wazuh cluster nodes):"
echo -e "  Frontend (ProxNET / Nginx):  ${BL}--net0 name=eth0,bridge=${SDN_BRIDGE},ip=dhcp,ip6=auto${CL}"
echo -e "  Cluster (Private SDN):       ${BL}--net1 name=eth1,bridge=${SDN_VNET_ID},ip=10.69.101.X/24${CL}"
echo -e "========================================================================\n"
